# 📘 Linear Algebra for Data Science - Practical Implementation

This notebook provides practical implementations of key **Linear Algebra** concepts used in **Data Science** and **Machine Learning**.
We will cover:

- **Vectors and Matrices** 📊
- **Linear Transformations** 🔄
- **Eigenvalues and Eigenvectors** 🔢
- **Matrix Decomposition (SVD & LU)** ⚡
- **Variance and Covariance** 📈

Let's dive into the power of Linear Algebra! 🚀


In [1]:
# Importing required libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.linalg import lu, svd
from numpy.linalg import eig


Matplotlib is building the font cache; this may take a moment.


## 📊 Vectors and Matrices

In [2]:
# Creating vectors and matrices with NumPy
vector = np.array([1, 2, 3])  # A 1D vector
matrix = np.array([[1, 2], [3, 4]])  # A 2x2 matrix

print("Vector:", vector)
print("Matrix:\n", matrix)


Vector: [1 2 3]
Matrix:
 [[1 2]
 [3 4]]


## 🔄 Linear Transformations

In [3]:
# Applying a linear transformation (Matrix Multiplication)
transformation_matrix = np.array([[2, 0], [0, 3]])
vector_2d = np.array([1, 2])

transformed_vector = transformation_matrix @ vector_2d  # Matrix-vector multiplication
print("Original Vector:", vector_2d)
print("Transformed Vector:", transformed_vector)


Original Vector: [1 2]
Transformed Vector: [2 6]


## 🔢 Eigenvalues and Eigenvectors

In [4]:
# Compute eigenvalues and eigenvectors
A = np.array([[4, -2], [1, 1]])
eigenvalues, eigenvectors = eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


## ⚡ Matrix Decomposition (SVD & LU)

In [5]:
# LU Decomposition
A = np.array([[4, 3], [6, 3]])
P, L, U = lu(A)

print("Lower Triangular Matrix (L):\n", L)
print("Upper Triangular Matrix (U):\n", U)


Lower Triangular Matrix (L):
 [[1.         0.        ]
 [0.66666667 1.        ]]
Upper Triangular Matrix (U):
 [[6. 3.]
 [0. 1.]]


In [6]:
# Singular Value Decomposition (SVD)
A = np.array([[1, 2], [3, 4], [5, 6]])
U, S, Vt = svd(A)

print("U:\n", U)
print("Singular Values (S):\n", S)
print("V Transposed (Vt):\n", Vt)


U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Singular Values (S):
 [9.52551809 0.51430058]
V Transposed (Vt):
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


## 📈 Variance and Covariance

In [7]:
# Compute variance and covariance matrix
data = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
df = pd.DataFrame(data, columns=['Feature1', 'Feature2', 'Feature3'])

variance = df.var()
covariance_matrix = df.cov()

print("Variance:\n", variance)
print("Covariance Matrix:\n", covariance_matrix)


Variance:
 Feature1    9.0
Feature2    9.0
Feature3    9.0
dtype: float64
Covariance Matrix:
           Feature1  Feature2  Feature3
Feature1       9.0       9.0       9.0
Feature2       9.0       9.0       9.0
Feature3       9.0       9.0       9.0


## 🎯 Conclusion

This notebook demonstrated **fundamental Linear Algebra concepts** with practical implementations in Python.  
These concepts are crucial for **dimensionality reduction (PCA)**, **data transformations**, **deep learning**, and many other applications in **Data Science**.  

Keep experimenting and exploring! 🚀  
